# Angular

## Install Angular
. VsCode öffnen
. Im Terminal von VsCode absetzen: "npm install -g @angular/cli"
. Im Terminal von VsCode absetzen: "ng new angular-blog-r-steger"
.. Standardmässige Optionen angwählen ausser bei "Which stylesheet format would you like to use?" dort muss "Sass (SCSS) [https://sass-lang.com/documentation/syntax#scss]" ausgewählt werden.


## Run Angular
Um die App lokal zu starten, muss man folgenden Command absetzen:
[source, shell]
----
ng serve --open
----

## Create Action to Deploy on Azure
. "Azure App Service" als Extension zu VsCode hinzufügen
. Unter Resourcen -> "Azure for Students" -> "Static Web Apps" -> rechtsklick machen und neue App Hinzufügen.
. Im Terminal von VsCode absetzen: "ng add @angular/material"


## Trouble Shooting 
. package.json mit Projektspezifischen Daten abfüllen
.. Im Terminal von VsCode absetzen: "npm init"
    Dadurch wird das package.json initialisierung und mit den Projektspezifischen einstellungen erweitert.
. Angular Versionen anpassen (Downgrade) ^20.0.0 -> ^19.2.0
.. Im Terminal von VsCode absetzen: "npm install"
    Dadruch werden die Abhängigkeiten von package-lock.json geupdatet
. angular.json angepasst
.. Variable "outputPath" hinzugefügt
.. Variable "index" hinzugefügt
. Problematischen Import entfernt
.. In der Datei "app.config.ts" wurde der Import "provideBrowserGlobalErrorListeners" verwendet. 
    Dieser ist aber vermutlich erst ab Angular Version 20.0.0 verfügbar. Aufgrund des Downgrades muss dieser Import entfernt werden. 

## Code-Qualitätstools hinzufügen
### ESLint
ESLint zum Projekt hinzufügen
[source, shell]
-----
ng add @angular-eslint/schematics
-----

### Prettier
Prettier zum Projekt hinzufügen
[source, shell]
-----
npm install prettier --save-dev
-----
Zusätzlich muss in package.json folgenden Code hinzugefügt werden:
[source, json]
----
"scripts": {
    "format": "npx prettier --write ./src/app/*"
}
----

### Environments
Environments zum Projekt hinzufügen
[source, shell]
-----
ng generate environments
-----

### Commitlint
Commitlint zum Projekt hinzufügen
[source, shell]
-----
npm install @commitlint/cli @commitlint/config-conventional
-----
Zusätzlich muss in package.json folgenden Code hinzugefügt werden:
[source, json]
----
"commitlint": {
 "extends": [
   "@commitlint/config-conventional"
 ]
}
----

### Lint-staged
Lint-staged zum Projekt hinzufügen
[source, shell]
-----
npm install --save-dev lint-staged
-----
Zusätzlich muss in package.json folgenden Code hinzugefügt werden:
[source, json]
----
"lint-staged": {
 "*.{ts,js,html}": "eslint --cache --fix",
 "*.{ts,js,html,css,scss,less,md}": "prettier --write"
}
----

### Husky
Husky zum Projekt hinzufügen
[source, shell]
-----
npm install --save-dev husky
-----
Husky initialisieren
[source, shell]
-----
npx husky init
-----
Zusätzlich muss in package.json folgenden Code hinzugefügt werden:
[source, json]
----
"scripts": {
 "prepare": "husky"
}
----
Nun muss das Vorbereitete Skript ausgeführt werden:
[source, shell]
-----
npm run prepare
-----
File ".husky/commit-msg" erstellen mit Folgendem Inhalt befüllen:
[source, shell]
----
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
npx --no-install commitlint --edit "$1"
----
In File ".husky/pre-commit" den Inhalt mit folgendem überschreiben
[source, shell]
-----
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
npx --no-install lint-staged
-----